### ISSUE TITLE
Determine how models should persist

### ISSUE THREAD

**Issue by atotalnoob** [chatbee/ChatPlatform#12]
ML Models should persist past reboots. Thus, they cannot live in any docker container, and must live in a non-volatile location. 

We should look into different ways to accomplish this.

**Comment by saucepleez** [comment]
This is accomplished by saving the model binary data (byte[]) into the database instead of to a zip file on the drive.

Add Migration for Model and MetaData
Add Training Model Loading => Load models immediately after training
Add Preload Models Method to App Startup => Scans configs and load all model IDs into Static List
Add Score Model Loading => Loads model dynamically when scoring a model that has not been loaded

**Comment by atotalnoob** [comment]
@saucepleez please comment on AB#7
